# Generated by Django 4.2.2 on 2023-06-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_helpsupport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=40)),
                ("website", models.CharField(max_length=40)),
                ("message", models.TextField()),
            ],
        ),
    ]
