# Generated by Django 4.2.2 on 2023-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nm", models.CharField(max_length=40)),
                ("em", models.EmailField(max_length=254)),
                ("pw", models.CharField(max_length=40)),
                ("cpw", models.CharField(max_length=40)),
            ],
        ),
    ]
