# Generated by Django 4.2.2 on 2023-06-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_user_register"),
    ]

    operations = [
        migrations.CreateModel(
            name="country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="data")),
            ],
        ),
        migrations.CreateModel(
            name="visa_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="data")),
                ("about", models.TextField()),
                ("doc", models.TextField()),
            ],
        ),
    ]
