# Generated by Django 4.2.2 on 2023-06-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_country_visa_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_register",
            name="cpw",
        ),
    ]
