# Generated by Django 4.2.2 on 2023-06-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_user_register_cpw"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_register",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="birthday",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="contact",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="country",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="gender",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="hobbies",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="pincode",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="qualifications",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="user_register",
            name="state",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
