# Generated by Django 4.2.2 on 2023-07-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_user_register_address_user_register_birthday_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("image", models.ImageField(blank=True, upload_to="data")),
                ("description", models.TextField()),
                ("writer", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="coaching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("overview", models.CharField(max_length=1000)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="data")),
                ("duration", models.CharField(max_length=500)),
                ("classes", models.CharField(max_length=500)),
                ("certificates", models.CharField(max_length=500)),
                ("cost", models.CharField(max_length=200)),
            ],
        ),
    ]
