# Generated by Django 4.2.2 on 2023-07-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_remove_country_id_alter_country_name_con_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="con_details",
            name="visa_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.visa_type",
            ),
            preserve_default=False,
        ),
    ]
