# Generated by Django 4.2.2 on 2023-07-05 17:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_con_visa_details_delete_con_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="coaching",
            name="certificates",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="coaching",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="coaching",
            name="overview",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="visa_type",
            name="about",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="visa_type",
            name="doc",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
