# Generated by Django 4.2.2 on 2023-07-06 05:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_alter_blogs_description_alter_coaching_certificates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
