# Generated by Django 4.2.2 on 2023-07-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_rename_image_visa_type_image1_visa_type_image2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coaching",
            name="classes",
        ),
    ]
