# Generated by Django 4.2.2 on 2023-07-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_remove_coaching_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coaching",
            name="certificates",
            field=models.TextField(),
        ),
    ]
