# Generated by Django 4.2.2 on 2023-07-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_alter_coaching_certificates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coaching",
            name="certificates",
        ),
    ]
