# Generated by Django 4.2.2 on 2023-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_remove_coaching_certificates"),
    ]

    operations = [
        migrations.CreateModel(
            name="eligible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=200)),
                ("lname", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=12)),
                ("status", models.CharField(max_length=100)),
                ("ocuupation", models.CharField(max_length=100)),
                ("cont", models.CharField(max_length=100)),
                ("visa", models.CharField(max_length=100)),
            ],
        ),
    ]
