# Generated by Django 4.2.2 on 2023-07-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_user_register_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_register",
            name="image",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
    ]
