# Generated by Django 4.2.2 on 2023-07-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0023_user_register_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="data"),
        ),
    ]
