# Generated by Django 4.2.2 on 2023-07-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_alter_user_register_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_register",
            name="files",
        ),
    ]
